version: '3'
services:
  app:
    image: srimani/raminus-website:1
    build: .
    volumes:
      - ./:/app
    ports:
      - "9005:9005"
    environment:
      - NODE_ENV=development
      - PORT=9005